name: ai-github-assistant
description: Summarize issues/PRs and suggest labels (CPU-optimized)
inputs:
  github_token:
    description: GitHub token
    required: true
  dashboard_url:
    description: Optional dashboard ingest URL
    required: false
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r $GITHUB_ACTION_PATH/requirements.txt
    - name: Run AI assistant
      shell: bash
      env:
        GITHUB_EVENT_PATH: ${{ github.event_path }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
        DASHBOARD_URL: ${{ inputs.dashboard_url }}
        HF_HOME: /tmp/hf_home
        TRANSFORMERS_CACHE: /tmp/hf_home
      run: |
        python $GITHUB_ACTION_PATH/main.py
