import os
import json
import requests
import time
from transformers import pipeline, logging

# suppress warnings
logging.set_verbosity_error()

# --- Environment setup ---
EVENT_PATH = os.getenv("GITHUB_EVENT_PATH")
REPO = os.getenv("GITHUB_REPOSITORY")
TOKEN = os.getenv("GITHUB_TOKEN")
DASHBOARD_URL = os.getenv("DASHBOARD_URL", "").strip()

HF_HOME = os.getenv("HF_HOME", "/tmp/hf_home")
os.environ.setdefault("HF_HOME", HF_HOME)
os.environ.setdefault("TRANSFORMERS_CACHE", HF_HOME)

if not EVENT_PATH or not REPO or not TOKEN:
    exit(0)

# --- Load GitHub Event Payload ---
with open(EVENT_PATH, "r", encoding="utf-8") as f:
    event = json.load(f)

is_issue = "issue" in event
is_pr = "pull_request" in event

if not (is_issue or is_pr):
    exit(0)

title = ""
body = ""
number = 0
etype = ""

# Check for PR first to avoid misdetection (PRs can contain issue objects)
if is_pr and event["pull_request"] is not None:
    obj = event["pull_request"]
    # Verify it's actually a PR by checking for head/base refs
    if "head" in obj and "base" in obj:
        title = obj.get("title", "") or ""
        body = obj.get("body", "") or ""
        number = obj["number"]
        etype = "pull_request"
    else:
        exit(0)
elif is_issue and event["issue"] is not None:
    obj = event["issue"]
    # Make sure it's not a PR masquerading as an issue
    if not obj.get("pull_request"):
        title = obj.get("title", "") or ""
        body = obj.get("body", "") or ""
        number = obj["number"]
        etype = "issue"
    else:
        exit(0)
else:
    exit(0)

text = (title + "\n\n" + body).strip()
if not text:
    text = "(empty)"

# --- Truncate to safe lengths ---
txt_for_sum = text[:1500]
txt_for_cls = text[:1200]

# --- Models (lightweight CPU) ---
SUM_MODEL = "sshleifer/distilbart-cnn-6-6"
CLS_MODEL = "valhalla/distilbart-mnli-12-1"

try:
    summarizer = pipeline("summarization", model=SUM_MODEL, device=-1)
except Exception:
    summarizer = pipeline("summarization", model=SUM_MODEL)

try:
    classifier = pipeline("zero-shot-classification", model=CLS_MODEL, device=-1)
except Exception:
    classifier = pipeline("zero-shot-classification", model=CLS_MODEL)

labels = ["bug", "feature", "documentation", "question", "enhancement", "refactor", "test", "ci", "security"]

def safe_post(url, headers, payload, retries=2, timeout=10):
    """Retry POST requests a few times before giving up"""
    for i in range(retries + 1):
        try:
            return requests.post(url, headers=headers, json=payload, timeout=timeout)
        except Exception:
            time.sleep(1)
    return None

# --- Summarize ---
try:
    s = summarizer(txt_for_sum, max_length=80, min_length=20, do_sample=False)
    summary = s[0]["summary_text"].strip()
except Exception:
    summary = txt_for_sum[:280] + ("..." if len(txt_for_sum) > 280 else "")

# --- Classify ---
try:
    pred = classifier(txt_for_cls, labels, multi_label=False)
    top_label = pred["labels"][0]
    score = float(pred["scores"][0])
except Exception:
    top_label = "question"
    score = 0.0

# --- Confidence description ---
def confidence_to_words(score: float) -> str:
    percent = score * 100
    if percent >= 80:
        return "I am very confident"
    elif percent >= 60:
        return "I am confident"
    elif percent >= 40:
        return "I am somewhat confident"
    elif percent >= 15:
        return "I am a bit confident"
    else:
        return "I am unsure"

confidence_words = confidence_to_words(score)

# --- Comment to GitHub ---
comment = f"""
### 🤖 RepoPilot Report

**📝 Summary**  
{summary}

## 📂 🎯 Predicted Category  
### 🟢 **This is most likely a {top_label.upper()} {etype.capitalize()}.**  
{confidence_words} with this prediction ({score * 100:.2f}% confidence).

**💡 Suggested Next Steps**  
- If this is a bug: try reproducing with minimal setup, then check logs.  
- If this is a feature request: clarify expected behavior and update docs.  
- If this is documentation: verify links, grammar, and completeness.  

**⚙️ Notes**  
This analysis was auto-generated by an AI workflow. Please verify before acting.
"""

headers = {
    "Authorization": f"token {TOKEN}",
    "Accept": "application/vnd.github+json"
}

try:
    post_url = f"https://api.github.com/repos/{REPO}/issues/{number}/comments"
    requests.post(post_url, headers=headers, json={"body": comment}, timeout=10)
except Exception:
    pass

# --- Add label (best effort) ---
try:
    label_url = f"https://api.github.com/repos/{REPO}/issues/{number}/labels"
    requests.post(label_url, headers=headers, json={"labels": [top_label]}, timeout=10)
except Exception:
    pass

# --- Push to Dashboard ---
if DASHBOARD_URL:
    try:
        payload = {
            "repo": REPO,
            "number": number,
            "type": etype,   
            "summary": summary,
            "label": top_label,
            "score": score,
            "title": title
        }
        _ = safe_post(
            DASHBOARD_URL.rstrip("/") + "/ingest",
            headers={"Content-Type": "application/json"},
            payload=payload
        )
    except Exception:
        pass